# Generated by Django 5.0.6 on 2024-05-26 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(db_column='admin_id', primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('callno', models.AutoField(db_column='callno', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('adviser', models.CharField(max_length=50)),
                ('abstract', models.CharField(max_length=1000)),
                ('sub_date', models.DateField()),
                ('college', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'thesis',
            },
        ),
        migrations.CreateModel(
            name='thesisapp_comments',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('theses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='thesisapp.thesis')),
            ],
            options={
                'verbose_name_plural': 'Thesis App Comments',
                'db_table': 'thesisapp_comments',
            },
        ),
    ]
